
package views;

import java.awt.Event;
import java.util.ArrayList;
import java.util.List;
import silabario.IViewEventListener;

public class ViewInfoHi extends javax.swing.JFrame {

     private List<IViewEventListener> listaEvent2;
     
    public ViewInfoHi() {
        initComponents();
        this.setLocationRelativeTo(null);
         
        listaEvent2 = new ArrayList<>();
    }

     public void addEventListener(IViewEventListener listener){
        listaEvent2.add(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(255, 51, 51));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 70, -1));

        jButtonBack.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 102, 102));
        jButtonBack.setText("Volver al Menú");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Microsoft YaHei", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Hiragana\n\nEl hiragana (平仮名 o ひらがな?) es uno de los dos silabarios empleados \nen la escritura japonesa; el otro se denomina katakana. También se \nsuele emplear hiragana para referirse a cualquiera de los caracteres \nde dicho silabario. Proviene de la simplificación de caracteres más \ncomplejos de origen chino que llegaron antes del comienzo del \naislamiento cultural japonés, que se mantuvo inflexible hasta el final \nde la era Edo. Se caracteriza por trazos curvos y simples.\n\nあ  a\tい  i\tう  u\tえ  e\tお  o\nか ka\tき ki\tく ku\tけ ke\tこ ko\nさ sa\tし shi\tす su\tせ se\tそ so\nた ta\tち chi\tつ tsu\tて te\tと to\nな na\tに ni\tぬ nu\tね ne\tの no\nは ha/wa\tひ hi\tふ fu/hu\tへ he/e\tほ ho\nま ma\tみ mi\tむ mu\tめ me\tも mo\nや ya\t\tゆ yu\t\tよ yo\nら ra\tり ri\tる ru\tれ re\tろ ro\nわ wa\t\t\t\tを wo/o\n\t\t\t\tん n\n\nが ga\tぎ gi\tぐ gu\tげ ge\tご go\nざ za\tじ ji\tず zu\tぜ ze\tぞ zo\nだ da\tぢ dji\tづ dzu\tで de\tど do\nば ba\tび bi\tぶ bu\tべ be\tぼ bo\nぱ pa\tぴ pi\tぷ pu\tぺ pe\tぽ po\n\nきゃ kya\t\tきゅ kyu\t\tきょ kyo\nしゃ sha\t\tしゅ shu\t\tしょ sho\nちゃ cha\t \tちゅ chu\t\tちょ cho\nにゃ nya\t\tにゅ nyu\t\tにょ nyo\nひゃ hya\t\tひゅ hyu\t\tひょ hyo\nみゃ mya\t\tみゅ myu\t\tみょ myo\nりゃ rya\t\tりゅ ryu\t\tりょ ryo\nぎゃ gya\t\tぎゅ gyu\t\tぎょ gyo\nじゃ ja\t\tじゅ ju\t\tじょ jo\nびゃ bya\t\tびゅ byu\t\tびょ byo\nぴゃ pya\t\tぴゅ pyu\t\tぴょ pyo\n\n\nCuando se hace referencia a ambos silabarios en conjunto, hiragana y \nkatakana, se conocen como kana. Estos caracteres, al contrario que los \nkanji, no tienen ningún valor conceptual, sino únicamente fonético.\n\nEste silabario se emplea en la escritura de palabras japonesas, \npartículas y desinencias verbales; en contraste con el katakana que se \nemplea para palabras extranjeras y onomatopeyas. Por ello, el hiragana \nes el primer silabario que aprenden los niños japoneses. A medida que \naprenden los kanji, los estudiantes van reemplazando los caracteres \nsilábicos en favor de los caracteres chinos.\n\nRef. Wikipedia.");
        jScrollPane1.setViewportView(jTextArea1);
        jTextArea1.setEditable(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 580, 350));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgHiragana/5imgJapan.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        for (int i = 0; i < listaEvent2.size(); i++) {

            IViewEventListener unEventoListen = listaEvent2.get(i);
            // Creamos un objeto Event con la informacion de lo que le sucedde
            // a la vista, por ejemplo. Se presiono un boton
            Event evento = new Event(evt, 0, evt);
            // El objeto event viaja hacia los que estan escuchando a la vista
            unEventoListen.listen(evento);
        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
